M48
; DRILL file {KiCad 9.0.6-9.0.6~ubuntu22.04.1} date 2026-06-23T21:31:26-0400
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-06-23T21:31:26-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6-9.0.6~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1181
%
G90
G05
T1
X9.335Y-1.6872
X9.5626Y-1.6872
T2
X9.002Y-1.6929
M30
