
[env:main]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
board_build.partitions = huge_app.csv
lib_deps = 
    bblanchon/ArduinoJson@^7.0.0

[env:simulation]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
board_build.partitions = huge_app.csv
build_flags = -DSIMULATE_ECU
lib_deps = 
    bblanchon/ArduinoJson@^7.0.0
